folderclean.py
start cmd.exe /k "chatlog1.py"
TIMEOUT /t 1 /nobreak
start cmd.exe /k "chatlog2.py"
TIMEOUT /t 1 /nobreak
start cmd.exe /k "chatlog3.py"
TIMEOUT /t 1 /nobreak
start cmd.exe /k "chatlog4.py"
TIMEOUT /t 1 /nobreak
start cmd.exe /k "chatlog5.py"
TIMEOUT /t 1 /nobreak
start cmd.exe /k "chatlog6.py"
TIMEOUT /t 1 /nobreak
start cmd.exe /k "chatlog7.py"
TIMEOUT /t 1 /nobreak
start cmd.exe /k "chatlog8.py"
TIMEOUT /t 1 /nobreak
start cmd.exe /k "chatlog9.py"
TIMEOUT /t 1 /nobreak
start cmd.exe /k "chatlog10.py"
TIMEOUT /t 1 /nobreak